services:
  apache:
    container_name: web
    image: debian_apache
    build: ../ProjetDocker/debian_apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password0
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
      MYSQL_DATABASE: bdd

    ports:
      - "3306:3306"

    volumes:
      - ./data:/var/lib/mysql

  phpmydmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

#network à créer