FROM debian:latest

RUN apt-get update && apt-get install -y \
    apache2 \
    php \
    libapache2-mod-php \
    php-mysql \
    && apt-get clean

COPY ./www /var/www/html

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
